-- Creating an INSTRUCTION table to hold the mock data for processing.
CREATE TABLE INSTRUCTION(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
ENTITY VARCHAR(255),
BUY_R_SELL CHAR(1),
AGREEDFIX DECIMAL(20, 2),
CURRENCY VARCHAR(25),
INSTUCTION_DATE DATE,
SETTLEMENT_DATE DATE,
UNITS INTEGER(40),
PRICE_PER_UNIT DECIMAL(40)
);